### ISSUE TITLE
Jupyter free version

### ISSUE THREAD

**Issue by teseoch** [skoch9/meshplot#2]
It would be nice to have the same viewer on an html generated file without the notebook.

A little bit like plotly

**Comment by jiangzhongshi** [comment]
This would be great to have. 
https://github.com/mrdoob/three.js/issues/4952 this looks relevant

**Comment by jiangzhongshi** [comment]
I looked up a bit, and it's possible to do the following
```
from ipywidgets.embed import embed_minimal_html
vw = viewer.plot(V,F, return_plot=True)
embed_minimal_html('temp.html',views=[vw._renderer])
```

**Comment by skoch9** [comment]
Supported with 4f29014683f53d9d63c7eb717b7692444b78094b.
