### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by pvnieo** [skoch9/meshplot#20]
Hi,

Thanks for the great library.

I don't know if I'm wrong, but now the library is only installable via conda. Is there a plan to add `pip` support.

Thank you in advance.

**Comment by jerdra** [comment]
you can just pip install it directly from the release package

i.e 
```
pip install https://github.com/skoch9/meshplot/archive/0.4.0.tar.gz
```

**Comment by pvnieo** [comment]
This works for me. Thanks.
Closing the issue!

**Comment by oliland** [comment]
Thanks for this - can I suggest that it's added to the README?
