### ISSUE TITLE
render directions

### ISSUE THREAD

**Issue by de-gozaru** [skoch9/meshplot#43]
Hi,

Thanks for the great library.

Is there a way to show the xyz directions, as in the image attached?

Thank you!

![image](https://user-images.githubusercontent.com/96230970/205282963-11e6d9ce-4ff3-4df1-accc-8202e888778f.png)

**Comment by de-gozaru** [comment]
Hi @jiangzhongshi 
any hint on this?
Thank you!

**Comment by jiangzhongshi** [comment]
Depending on what you would like
1. Use the add lines function to add three lines from x,y,z to x+1, y, z and assign colors.

2. If you want the fancy ones, then you may want to find the meshes for them or create in blender. Then use add meshes
